all: \
a

compile:
	gcc -o sud2sat.out sud2sat.c
	gcc -o sat2sud.out sat2sud.c
a:
	gcc -o sud2sat.out sud2sat.c
	./sud2sat.out inputfiles/grid02.txt

b:
	gcc -o sat2sud.out sat2sud.c
	./sat2sud.out first.out

clean:
	rm first.in
	rm sud2sat.out

target:
	
